### ISSUE TITLE
Command NPC don't saved

### ISSUE THREAD

**Issue by CarlosN27** [MrMaurice211/BungeeNPC#30]
# Make sure the info are filled before submitting your issue! Thank you!

### Check your server version
- [ ] Spigot 1.8.8
- [ ] Spigot 1.9.4
- [ ] Spigot 1.10.2
- [ ] Spigot 1.11.2
- [ ] Spigot 1.12.2
- [ ] Spigot 1.13.2
- [ ] PaperSpigot 1.8.8
- [ ] PaperSpigot 1.9.4
- [ ] PaperSpigot 1.10.2
- [ ] PaperSpigot 1.11.2
- [ ] PaperSpigot 1.12.2
- [x] PaperSpigot 1.13.2

### Put here your plugin version, seen with /bnpc plugin, if the command isnt available is because you dont have the latest version!
BungeeNPC 1.3.9.3

### Console show any error?
- [x ] Yes
- [ ] No

[pastebin](https://pastebin.com/)
Pastebin not loading.
The error is this:
Error loading the file Bloques with error: Cannot start instance of me.mrmaurice.bnpc.npc.NPCCmd
`[01:20:57 WARN]: java.lang.reflect.InvocationTargetException
[01:20:57 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:20:57 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:20:57 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:20:57 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[01:20:57 WARN]: at me.mrmaurice.bnpc.utils.Reflections$MethodInvoker.invoke(Reflections.java:336)
[01:20:57 WARN]: at me.mrmaurice.bnpc.config.JsonConfig$SerializableJsonValue.getSer(JsonConfig.java:142)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.INPC.loadConfig(INPC.java:181)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.NPCCmd.loadConfig(NPCCmd.java:73)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.INPC.<init>(INPC.java:51)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.NPCCmd.<init>(NPCCmd.java:29)
[01:20:57 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:20:57 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:20:57 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:20:57 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:20:57 WARN]: at me.mrmaurice.bnpc.utils.Reflections$ConsInvoker.newInstance(Reflections.java:367)
[01:20:57 WARN]: at me.mrmaurice.bnpc.managers.DataManager.<init>(DataManager.java:43)
[01:20:57 WARN]: at me.mrmaurice.bnpc.BungeeNPC.onEnable(BungeeNPC.java:82)
[01:20:57 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[01:20:57 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[01:20:57 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[01:20:57 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[01:20:57 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[01:20:57 WARN]: at java.lang.Thread.run(Thread.java:748)
[01:20:57 WARN]: Caused by: java.lang.IllegalArgumentException: unknown world
[01:20:57 WARN]: at org.bukkit.Location.deserialize(Location.java:1083)
[01:20:57 WARN]: ... 28 more
[01:20:57 WARN]: java.lang.reflect.InvocationTargetException
[01:20:57 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:20:57 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:20:57 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:20:57 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:20:57 WARN]: at me.mrmaurice.bnpc.utils.Reflections$ConsInvoker.newInstance(Reflections.java:367)
[01:20:57 WARN]: at me.mrmaurice.bnpc.managers.DataManager.<init>(DataManager.java:43)
[01:20:57 WARN]: at me.mrmaurice.bnpc.BungeeNPC.onEnable(BungeeNPC.java:82)
[01:20:57 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[01:20:57 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[01:20:57 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[01:20:57 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[01:20:57 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[01:20:57 WARN]: at java.lang.Thread.run(Thread.java:748)
[01:20:57 WARN]: Caused by: me.mrmaurice.bnpc.utils.Reflections$ReflectionException: Cannot invoke the method deserialize
[01:20:57 WARN]: at me.mrmaurice.bnpc.utils.Reflections$MethodInvoker.invoke(Reflections.java:339)
[01:20:57 WARN]: at me.mrmaurice.bnpc.config.JsonConfig$SerializableJsonValue.getSer(JsonConfig.java:142)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.INPC.loadConfig(INPC.java:181)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.NPCCmd.loadConfig(NPCCmd.java:73)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.INPC.<init>(INPC.java:51)
[01:20:57 WARN]: at me.mrmaurice.bnpc.npc.NPCCmd.<init>(NPCCmd.java:29)
[01:20:57 WARN]: ... 18 more
[01:20:57 WARN]: me.mrmaurice.bnpc.utils.Reflections$ReflectionException: Cannot start instance of me.mrmaurice.bnpc.npc.NPCCmd
[01:20:57 WARN]: at me.mrmaurice.bnpc.utils.Reflections$ConsInvoker.newInstance(Reflections.java:370)
[01:20:57 WARN]: at me.mrmaurice.bnpc.managers.DataManager.<init>(DataManager.java:43)
[01:20:57 WARN]: at me.mrmaurice.bnpc.BungeeNPC.onEnable(BungeeNPC.java:82)
[01:20:57 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[01:20:57 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[01:20:57 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[01:20:57 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[01:20:57 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[01:20:57 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[01:20:57 WARN]: at java.lang.Thread.run(Thread.java:748)`

### Please describe when and how the error happen if possible!
The error occurs when I restart or shut down the server

**Comment by CarlosN27** [comment]
My bad.... not active bungeecord on spigot.yml
