### ISSUE TITLE
1.13 update?

### ISSUE THREAD

**Issue by FrankHeijden** [MrMaurice211/BungeeNPC#6]
### Server version:
Spigot 1.13

### BungeeNPC version:
1.3.8

### Error:
https://hastebin.com/ahiwisevef.css

### Description:
Start the server with spigot 1.13 :P

**Comment by MrMaurice211** [comment]
Well that version wasnt 1.13 compatible, but now it is (1.3.9)

**Comment by FrankHeijden** [comment]
`[21:05:02] [Server thread/INFO]: FrankHeijden issued server command: /bnpc create test bungee test
[21:05:02] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:05:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.utils.Reflections$ConsInvoker.newInstance(Reflections.java:363)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.managers.EntityManager.createNPC(EntityManager.java:39)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.npc.INPC.create(INPC.java:67)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.npc.NPCBungee.create(NPCBungee.java:44)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.cmds.subcmd.CreateCmd.run(CreateCmd.java:61)
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:05:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.utils.Reflections$MethodInvoker.invoke(Reflections.java:332)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.cmds.CmdManager.onCommand(CmdManager.java:46)
[21:05:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:05:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:05:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[21:05:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[21:05:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[21:05:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[21:05:02] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[21:05:02] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelConfig.setRecvByteBufAllocator(DefaultChannelConfig.java:313)
[21:05:02] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:73)
[21:05:02] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:69)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.nms.v1_13_R2.network.EmptyChannel.<init>(EmptyChannel.java:14)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.nms.v1_13_R2.network.EmptyNetworkManager.<init>(EmptyNetworkManager.java:12)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.nms.v1_13_R2.EntityNMSNPC.createEntity(EntityNMSNPC.java:54)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.nms.EntityNPC.<init>(EntityNPC.java:34)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.nms.v1_13_R2.EntityNMSNPC.<init>(EntityNMSNPC.java:35)
[21:05:02] [Server thread/WARN]: 	... 31 more
[21:05:02] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:05:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:05:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.utils.Reflections$MethodInvoker.invoke(Reflections.java:332)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.cmds.CmdManager.onCommand(CmdManager.java:46)
[21:05:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:05:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:05:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[21:05:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[21:05:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[21:05:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[21:05:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[21:05:02] [Server thread/WARN]: Caused by: me.mrmaurice.bnpc.utils.Reflections$ReflectionException: Cannot start instance of me.mrmaurice.bnpc.nms.v1_13_R2.EntityNMSNPC
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.utils.Reflections$ConsInvoker.newInstance(Reflections.java:366)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.managers.EntityManager.createNPC(EntityManager.java:39)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.npc.INPC.create(INPC.java:67)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.npc.NPCBungee.create(NPCBungee.java:44)
[21:05:02] [Server thread/WARN]: 	at me.mrmaurice.bnpc.cmds.subcmd.CreateCmd.run(CreateCmd.java:61)
[21:05:02] [Server thread/WARN]: 	... 22 more
[21:05:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bnpc' in plugin BungeeNPC v1.3.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: me.mrmaurice.bnpc.utils.Reflections$ReflectionException: Cannot invoke the method run
	at me.mrmaurice.bnpc.utils.Reflections$MethodInvoker.invoke(Reflections.java:335) ~[BungeeNPC-1.3.9.jar:?]
	at me.mrmaurice.bnpc.cmds.CmdManager.onCommand(CmdManager.java:46) ~[BungeeNPC-1.3.9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
	... 15 more`

**Comment by FrankHeijden** [comment]
Error when just even creating a basic NPC.... https://paste.md-5.net/gojigapiru.vbs

**Comment by FrankHeijden** [comment]
Do you test your stuff?

**Comment by FrankHeijden** [comment]
This is on a clean install, just dropped the jar in and executed the command, lol

**Comment by MrMaurice211** [comment]
> 
> 
> Do you test your stuff?

Not as i want to, not enought time :/

The bug is fixed, check it out the page
Thanks.

**Comment by FrankHeijden** [comment]
no not fixed: https://paste.md-5.net/pacivihuxe.vbs
